server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: books-service
          uri: lb://books-service
          predicates:
            - Path=/books/*
          filters:
            - TokenRelay=
    azure:
      active-directory:
        profile:
#          tenant-id: <your-Azure-AD-Tenant>
#        credential:
#          client-id: <your-application-ID-of-Books>
#        app-id-uri: <your-application-ID-URI-of-Books>
          tenant-id: 0a2ede99-b592-4e1c-a0ee-283b3a172a61
        credential:
          client-id: ed89fb04-ca69-45dc-ae83-990b7f21cb11
        app-id-uri: api://books

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

debug: on
